apiVersion: apps/v1
kind: Deployment
metadata: 
  name: test-deployment
  namespace: test
  labels: 
    app: test-web
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: test-web
  template:
    metadata:
      labels: 
        app: test-web
    spec:
      containers:
      - name: test-container
        image: ngnix:latest
        ports:
        - containerport: 80
        env: 
          - name: USRENAME
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: password
        volumeMounts:
        - name: test-volume
          mountPath: /tmp/test
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits: 
            memory: "200Mi"
            cpu: "200m"
      volumes: 
      - name: test-volume
        emptyDir: {}